### ISSUE TITLE
Feature request: add search 

### ISSUE THREAD

**Issue by Pauler221** [yasinkacmaz/jetflix#195]
It would be really nice to be able so search for a movie name. Otherwise great app!

**Comment by yasinkacmaz** [comment]
Hello @Pauler221 thanks for the feedback. I tried integrating search in this app. I even have a branch here: [feat/search](https://github.com/yasinkacmaz/jetflix/tree/feat/search)
The thing is TMDB discover endpoint didn't have **query** parameter at that time. I have a commit with this message:
[BLOCKED (You cannot have query parameter at tmdb discover endpoint)](https://github.com/yasinkacmaz/jetflix/commit/1cc170d1bfdd8c9b47dc5ae725f8af52e2fa0588)

I will read TMDB API documentation more and will inform you if there is another way around.

**Comment by Didiloy** [comment]
Hello @yasinkacmaz thanks for your comitment. The search function is  also something I will love to see.
I think maybe this endpoint https://developers.themoviedb.org/3/search/search-movies is what you are looking for ?
Keep up the good work !

**Comment by yasinkacmaz** [comment]
@Didiloy I saw search-movies endpoint as well, thanks. With what I found so far, I have 2 options:

1) Add a search layout to appbar and go to `search` endpoint when a query is entered, otherwise, go to `discover` endpoint
2) Have a search button/layout and open a different search UI when clicked like Google does for example in Keep Notes.

Which one you would prefer? 

A quick note: TMDB includes TV movies only for these two endpoints. TV series have their separate endpoint

**Comment by yasinkacmaz** [comment]
I am more leaning towards the first approach, it may require some adjustments though. For example, filters should not be applicable to the search.
It will contain only movies now. I am planning to add TV series in the future.

**Comment by yasinkacmaz** [comment]
Hey @Pauler221 @Didiloy, I've created a pull request for the search feature.  Here you can see the details: [https://github.com/yasinkacmaz/jetflix/pull/196](https://github.com/yasinkacmaz/jetflix/pull/196)

**Comment by Didiloy** [comment]
That's really great thank you !
